on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      # ESTO EQUIVALE AL "npm i" QUE DICE LA DOCS
      - name: Install Antora and Lunr Extension
        run: npm install

      # AHORA SÍ PODRÁS COPIAR PORQUE YA EXISTE LA CARPETA
      - name: Prepare Lunr Extension
        run: |
          mkdir -p supplemental-ui
          cp -R node_modules/@antora/lunr-extension/supplemental_ui/* supplemental-ui/

      - name: Build Antora project
        run: npx antora local-antora-playbook.yml --fetch